title: 32bitFlame's Blog but also not
email: benjamess2004@gmail.com
description: >-
 Ben AKA 32bitFlame's Programming Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://32bitFlame.github.io"
github_username:  32BitFlame

remote_theme: "32BitFlame/beautiful-jekyll"
plugins:
  - jekyll-feed
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false

